Possible fix for #11
adafruit/Adafruit_CircuitPython_TCA9548A pull request #12
Opened 2019-07-25 18:48 UTC by caternuson

Can't just add logic in existing function since it would still `hasattr`. Need to dynamically provide it as needed.

Don't have an INA219 to test with original issue, but tested with an I2C FRAM and TCA:
**tca_fram_test.py**
```python
import board
import adafruit_fram
import adafruit_tca9548a

tca = adafruit_tca9548a.TCA9548A(board.I2C())

fram = adafruit_fram.FRAM_I2C(tca[0])

fram[0] = 1
print(fram[0])
```
 **RPI/Blinka**
```python
pi@pizerow:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tca_fram_test
bytearray(b'\x01')
>>>
```
**ItsyM4/CP**
```python
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.2 on 2019-06-27; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import tca_fram_test
bytearray(b'\x01')
>>>
```

2019-07-25 18:50 UTC, ladyada approved these changes

2019-07-25 18:50 UTC, ladyada commented
i thought we added it to blinka?

2019-07-25 18:51 UTC, ladyada commented
oh right its on blinka (required) but not busio.

2019-07-25 18:53 UTC, caternuson commented
Yep. And that all worked. New issue is that it can then fail on native CP since `I2CDevice` will try to call the linux func.

2019-07-25 21:11 UTC, tannewt requested changes
I think we always want writeto_then_readfrom available so that drivers are written for it going forwards. (Otherwise they won't work with Blinka.)

So, on this PR detect in writeto_then_readfrom or in the constructor whether it is available and provide a substitute. Bonus points for adding writeto_then_readfrom into CircuitPython too. Thanks!

2019-07-25 22:53 UTC, caternuson commented
Don't most drivers use `I2CDevice` and call `write_then_readinto`? It's then `I2CDevice` that turns that into platform specific calls. With the current logic, the simple existence of `writeto_then_readfrom` is seen as being linux:
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/master/adafruit_bus_device/i2c_device.py#L145
Without changing that logic, this class needs to behave dynamically. So it's checking with `hasattr` and providing with `setattr`.

And in the future, when `writeto_then_readfrom` gets added to `busio.I2C`, it would still work.

2019-07-26 07:28 UTC, tannewt commented
Yes, most do but this driver shouldn't assume I2CDevice is used (just like busio.I2C shouldn't.) It should always provide writeto_then_readfrom even if the underlying I2C bus doesn't. As is, it only adds it when the underlying implementation has it. Doing it only sometimes risks people writing code that won't work on Blinka.

I created a PR to remove stop= from CircuitPython in favor of writeto_then_readfrom here: https://github.com/adafruit/circuitpython/pull/2012

2019-07-29 14:28 UTC, caternuson commented
Is this PR even needed then? If CP's busio.I2C provides `writeto_then_readfrom`, then the existing version will just start working.

2019-07-30 20:12 UTC, tannewt commented
It'll be needed for older versions. Want me to wrap it up?

2019-07-30 22:54 UTC, caternuson commented
Sure. Works for me.

2019-08-06 02:08 UTC, tannewt commented
@caternuson I've commited to your branch with what I think will work. Please let me know what you think. Thanks!

2019-08-06 15:43 UTC, caternuson commented
Ah, OK. I think I was trying to avoid duplicating the logic from `I2CDevice` and just drive the behavior from here. 

Not sure what it would be - but can you think of any issues in the future if the code in `I2CDevice.writeto_then_readfrom` changes and then code here is not updated to match?

2019-08-06 21:09 UTC, tannewt commented
Ah, I think it's ok to duplicated it since it's temporary. There is no guarantee the this is used with I2CDevice so it's better to have this updated now.

I can't think of any issues but we can always fix things if it comes up.

2019-08-06 21:12 UTC, caternuson commented
OK, cool with me. I just took care of the minor lints.

2019-08-06 21:17 UTC, tannewt commented
Thanks! I totally missed that it had issues.

2019-08-06 21:18 UTC, tannewt approved these changes

2019-08-06 21:18 UTC, merged