Adds initial working code.
adafruit/Adafruit_CircuitPython_TCA9548A pull request #2
Opened 2018-08-14 20:49 UTC by caternuson

This is a second PR to see if Travis kicks in.

2018-08-15 17:11 UTC, sommersoft requested changes
Other than these two "administrivia" things, looks excellent to me. We need to update the cookiecutter with these two changes; I plan on doing that tonight.

2018-08-15 17:11 UTC, sommersoft commented on .pylintrc
> +ignored-modules=
While a patch is in work to do this, can you add `board` to the ignored-modules? This will cover future PyPi work.

2018-08-15 17:11 UTC, sommersoft commented on .travis.yml
> +
Could you change this to:
```
- pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
```
While pylint is currently happy, who knows what will get added in future versions. :smile:

2018-08-15 17:27 UTC, tannewt requested changes
Thank you for adding this! I think it'll be helpful. Just a few comments now.

2018-08-15 17:27 UTC, tannewt commented on adafruit_tca9548a.py
> +
Add:
```python
def __len__(self):
    return 8
```
That way it can be iterated over.

2018-08-15 17:27 UTC, tannewt commented on adafruit_tca9548a.py
> +            raise ValueError("Channel must be an integer in the range: 0-7")
IndexError instead since its a sequence.

2018-08-15 17:27 UTC, tannewt commented on adafruit_tca9548a.py
> +            raise ValueError("Channel already in use.")
I wouldn't track this because you could have multiple devices on a single channel. The locking should prevent bus usage conflicts.

2018-08-15 17:27 UTC, tannewt commented on adafruit_tca9548a.py
> +        return TCA9548A_Channel(self, key)
I would cache the channel so the same object is returned for the same accesses.

2018-08-15 17:27 UTC, tannewt commented on requirements.txt
> +adafruit-circuitpython-busdevice
This isn't a dependency because its not imported by adafruit_tca9548c.py.

2018-08-16 01:18 UTC, sommersoft approved these changes
My 2 requests are good now. Thanks @caternuson!

2018-08-24 05:36 UTC, tannewt approved these changes
Thanks! Sorry for the slow review!

2018-08-24 05:36 UTC, merged