Bugfix Channel Scan
adafruit/Adafruit_CircuitPython_TCA9548A pull request #32
Opened 2021-05-07 10:19 UTC by codenio

This PR addresses #31 ,
- Fixes Bug with Channel scan

**Bug:** It Performs i2c scan on actual i2c bus where TCA9548A is connected
```
$ python i2c-mux.py 
['0x70']
['0x70']
Press Entre to exit..
```

**Fix:** Perform i2c scan on selected channel
```shell
$ python i2c-mux.py 
['0x70']
['0x60', '0x70'] #MCP4725 DAC module is connected to channel 0 of TCA9548A
Press Entre to exit..
```

2021-05-07 16:46 UTC, jposada202020 commented
Thanks for your contribution :)

2021-05-07 18:32 UTC, jposada202020 commented
@codenio I do not have this particular hardware, it seems that you have, is that correct? if so I could take a look at the datasheet and see the changes made,as I could not test. let me know thanks.

2021-05-07 18:36 UTC, codenio commented
> @codenio I do not have this particular hardware, it seems that you have, is that correct? if so I could take a look at the datasheet and see the changes made,as I could not test. let me know thanks.

yes @jposada202020 , I have this hardware with me, and the Bug and FIx mentioned earlier are results from hardware.

2021-05-07 18:39 UTC, jposada202020 commented
Good take a look to the Datasheet tonight to see what we are talking about here. Thanks

2021-05-07 18:41 UTC, codenio commented
I can add the entire code used for testing and its results in this thread by tomorrow

2021-05-07 18:43 UTC, jposada202020 commented
Yes, as mentioned in the other PR, we like to include new examples that way people coulddiscover the new features.

2021-05-08 15:45 UTC, jposada202020 commented
I took a look, at the datasheet, if you have the test code that would be great. Thanks

2021-05-08 16:31 UTC, codenio commented
Added Text code and added the same in examples.rst :+1:

2021-05-08 17:07 UTC, codenio commented
Mocked Test Code : examples/tca9548a_channelscan.py
It uses [VPi](https://github.com/codenio/virtual-pi) (Virtual-Pi) Package for testing with mock adafruit_tca9548a library

```python
# This example shows scanning of each TCA9548A channels.
try:
  import board
  import busio
  import adafruit_tca9548a
except:
  import VPi.board as board
  import VPi.busio as busio
  import VPi.adafruit_tca9548a as adafruit_tca9548a
    
# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# Scan the Main I2C Channel present in your board
print(f"Scan of Main I2C Channel:{[hex(i) for i in i2c.scan()]}")

# Scan Each TCA9548A channel
for i in range(8):
    print(f"Scan of TCA[{i}] Channel: {[hex(j) for j in tca[i].scan()]}")

```


```shell
$ python examples/tca9548a_channelscan.py
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0xec', '0x70']
Scan of TCA[1] Channel: ['0x55', '0x70']
Scan of TCA[2] Channel: ['0xeb', '0xc5', '0x70']
Scan of TCA[3] Channel: ['0xe0', '0x70']
Scan of TCA[4] Channel: ['0x4a', '0x19', '0x91', '0x70']
Scan of TCA[5] Channel: ['0x14', '0x70']
Scan of TCA[6] Channel: ['0xfe', '0xfd', '0x9a', '0x70']
Scan of TCA[7] Channel: ['0x5b', '0x7', '0x70']
```

2021-05-10 14:38 UTC, jposada202020 commented
@codenio I will test this change with hardware on hand at the end of this week, also I want to see if this could help be or not an issue in the VL53L0X library.  Also just, after discussion last week, because M0 boards does not have f-strings, we would avoid them in the example code.. We have just change our design guide last week. Thanks and sorry for that last minute change
https://github.com/adafruit/circuitpython/blob/main/docs/design_guide.rst

2021-05-10 16:13 UTC, codenio commented
> @codenio I will test this change with hardware on hand at the end of this week, also I want to see if this could help be or not an issue in the VL53L0X library. Also just, after discussion last week,

Sure will take a look

> because M0 boards does not have f-strings, we would avoid them in the example code.. We have just change our design guide last week. Thanks and sorry for that last minute change
> https://github.com/adafruit/circuitpython/blob/main/docs/design_guide.rst

Replaced fstrings with format :+1:

2021-05-10 16:15 UTC, jposada202020 commented
Thanks I have to re-submit one of my own PRs 😄 . question could you Mock-up test try to mock this issue?
https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X/issues/27. Just asking :)

2021-05-10 16:20 UTC, codenio commented
on it already, suggesting some debugging tips there.

2021-05-13 02:03 UTC, jposada202020 requested changes
I review the present code. 
I test this with the following hardware

### Hardware
* Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
* Adafruit TCA9548A
* Adafruit MMA8451

Procedure:
1. First I used the followig code modfied from the simpletest to verify was ok

```python
import time
import board
import adafruit_mma8451
import adafruit_tca9548a
# import tca9548a_simpletest

i2c = board.I2C()
tca = adafruit_tca9548a.TCA9548A(i2c)
sensor = adafruit_mma8451.MMA8451(tca[1])

while True:
    x, y, z = sensor.acceleration
    print(
        "Acceleration: x={0:0.3f}m/s^2 y={1:0.3f}m/s^2 z={2:0.3f}m/s^2".format(x, y, z)
    )
    time.sleep(1)
```

#### Results:

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_simpletest
Acceleration: x=-0.105m/s^2 y=0.962m/s^2 z=9.883m/s^2
Acceleration: x=-0.081m/s^2 y=1.030m/s^2 z=9.807m/s^2
Acceleration: x=-0.053m/s^2 y=1.030m/s^2 z=9.725m/s^2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_simpletest.py", line 29, in <module>
KeyboardInterrupt: 
>>> 
```

After that I used the example provided `tca9548a_channelscan.py` provided in the PR

#### Results

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import tca9548_scantest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548_scantest.py", line 16, in <module>
RuntimeError: Function requires lock
>>> 
```

I tried to add i2c.lock, and unlock to allow the bus to do the scan

#### Results

```python
>>> import tca9548_scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x8', '0x70']
Scan of TCA[7] Channel: ['0x70']
>>> 
```

However the MMA8451 is located at [1] as shown in the picture
![image](https://user-images.githubusercontent.com/34255413/118067023-bd14db80-b36d-11eb-86f8-27d10c37e725.png)

2021-05-13 04:28 UTC, codenio commented
@jposada202020 ,  happy to see your reviews, I have the following comments

- is Active Low RESET of TCA9548A is pulled up to 5v ..? with Pulling it up TCA9548A can react abnormally (from my experience)
- it is observable that, connected MMA8451 appears in the 2nd channel not from first but from last.

Further Testing Required. can you try with pulling up RESET..?

2021-05-13 12:06 UTC, jposada202020 commented
1. You are right it needs a pull-up resistor. Adafruit TCA9548A Breakout already has taken this into consideration. see https://cdn-learn.adafruit.com/assets/assets/000/027/693/original/adafruit_products_schem.png?1442010910
2. I could for sure. I work on that in the next days. 
Thanks

2021-05-13 13:29 UTC, codenio commented
> 1. You are right it needs a pull-up resistor. Adafruit TCA9548A Breakout already has taken this into consideration. see https://cdn-learn.adafruit.com/assets/assets/000/027/693/original/adafruit_products_schem.png?1442010910

I had the same feeling that, it is taken care at the design level until I had issues with the Breakout Board, It would partially detect and would go into reset state in random intervals (may be specific to my environment or setup). so decided to pull it up externally and it started working fine.

2021-05-13 19:26 UTC, jposada202020 commented
Gotcha, we will see

2021-05-23 01:51 UTC, jposada202020 commented
I did a retake on this

# Wiring
![image](https://user-images.githubusercontent.com/34255413/119245367-db858e80-bb46-11eb-9038-b90f83980e13.png)

# Results
This PR works, with a SAMD51, and the nRF52840, however it does not work for the RP2040. I tested this with the code mentioned above, and with a modified simpletest to include two sensor and not one. Sensor were a BH1750 and a MMA8451

##SAMD51
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather M4 Express with samd51j19
>>> import tca9548_scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x1d', '0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x23', '0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
```

```python
>>> import tca9548a_simpletest
Acceleration: x=-0.283m/s^2 y=1.097m/s^2 z=9.821m/s^2
346.67 Lux
Acceleration: x=-0.354m/s^2 y=1.087m/s^2 z=9.797m/s^2
345.83 Lux
```

## RP2040

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import tca9548_scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
```

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_simpletest.py", line 11, in <module>
  File "/lib/adafruit_bh1750.py", line 164, in __init__
ValueError: No I2C device at address: 23
```

## nRF52840

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather nRF52840 Express with nRF52840
>>> import tca9548a_simpletest
Acceleration: x=-0.273m/s^2 y=1.135m/s^2 z=9.802m/s^2
322.08 Lux
```

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather nRF52840 Express with nRF52840
>>> import tca9548_scantest
Scan of Main I2C Channel:['0x8', '0x70']
Scan of TCA[0] Channel: ['0x8', '0x70']
Scan of TCA[1] Channel: ['0x8', '0x1d', '0x70']
Scan of TCA[2] Channel: ['0x8', '0x70']
Scan of TCA[3] Channel: ['0x8', '0x70']
Scan of TCA[4] Channel: ['0x8', '0x23', '0x70']
Scan of TCA[5] Channel: ['0x8', '0x70']
Scan of TCA[6] Channel: ['0x8', '0x70']
Scan of TCA[7] Channel: ['0x8', '0x70']
>>> 
```


## Test Code

```python
import time
import board
import adafruit_mma8451
import adafruit_tca9548a
import adafruit_bh1750

i2c = board.I2C()
tca = adafruit_tca9548a.TCA9548A(i2c)
sensor = adafruit_mma8451.MMA8451(tca[1])
sensor2 = adafruit_bh1750.BH1750(tca[4])

while True:
    x, y, z = sensor.acceleration
    print(
        "Acceleration: x={0:0.3f}m/s^2 y={1:0.3f}m/s^2 z={2:0.3f}m/s^2".format(x, y, z)
    )
    time.sleep(1)
    print("%.2f Lux" % sensor2.lux)
    time.sleep(1)

```

2021-05-23 01:53 UTC, jposada202020 commented
So basically this work, and there is maybe a bug in the RP2040

2021-05-23 01:59 UTC, jposada202020 approved these changes

2021-05-23 11:18 UTC, jerryneedell commented
I am trying to run this PR on a feather m4 express and a feather rp2040 but I am a bit confused about actual code used for the "scantest" When I try the tca9548a_channelscan.py from the repository on the Feather_m4 I get 
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather M4 Express with samd51j19
>>> 
>>> import tca9548a_channelscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_channelscan.py", line 16, in <module>
RuntimeError: Function requires lock
>>> 
```
with this PR installed.
What code are you using for the test?

2021-05-23 11:52 UTC, jposada202020 commented
You are right I mentioned regarding the lock in previous comments but I never actually put the code. here the modified code

```python
# SPDX-FileCopyrightText: 2021 codenio (Aananth K)
# SPDX-License-Identifier: MIT

# This example shows scanning of each TCA9548A channels.
import board
import busio
import adafruit_tca9548a

# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# Scan the Main I2C Channel present in your board
i2c.try_lock()
print("Scan of Main I2C Channel:{}".format([hex(i) for i in i2c.scan()]))
i2c.unlock()

# Scan Each TCA9548A channel
for i in range(8):
    print("Scan of TCA[{}] Channel: {}".format(i, [hex(j) for j in tca[i].scan()]))
```

2021-05-23 12:31 UTC, jerryneedell commented
I can confirm the same problematic behavior on the rp2040
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather M4 Express with samd51j19
>>> 
>>> import scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x5e', '0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x23', '0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
>>> 


Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
>>> 

```

2021-05-23 12:43 UTC, jposada202020 commented
Thanks, strange.. I added this to our  Weekly meeting

2021-05-23 12:44 UTC, jerryneedell commented
however, the mux works OK on the RP2040
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test
X: 0.0, Y: 0.098, Z: 0.0 mT
109.58 Lux
X: 0.0, Y: 0.098, Z: -0.098 mT
111.25 Lux
X: 0.196, Y: 0.196, Z: 0.0 mT
111.25 Lux
X: 0.196, Y: -0.098, Z: 0.0 mT
111.25 Lux
X: -0.098, Y: 0.098, Z: -0.098 mT
111.25 Lux
X: 0.0, Y: -0.098, Z: -0.098 mT
111.25 Lux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test.py", line 28, in <module>
KeyboardInterrupt: 
>>> 

I have a bht1750 and a tlv493d attached running this code
```
import time
import board
import busio
import adafruit_tca9548a
import adafruit_bh1750
import adafruit_tlv493d


# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# For each sensor, create it using the TCA9548A channel instead of the I2C object
bh = adafruit_bh1750.BH1750(tca[4])
tlv = adafruit_tlv493d.TLV493D(tca[1])

# After initial setup, can just use sensors as normal.
while True:
    print("X: %s, Y: %s, Z: %s mT" % tlv.magnetic)
    print("%.2f Lux" % bh.lux)
    time.sleep(1)
```

2021-05-23 12:49 UTC, jposada202020 commented
@codenio as jerryn mentions we would need to modify the code in the example to include the lock as shown in the example above in order to this to work. thanks

2021-05-23 12:51 UTC, jposada202020 requested changes
@codenio as jerryn mentions we would need to modify the code in the example to include the lock as shown in the example above in order to this to work. thanks

2021-05-23 12:53 UTC, jerryneedell commented
even stranger - I plugged in the rp2040 and did 2 scans with different (incorrect) results
```
 
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x8', '0x23', '0x70']
Scan of TCA[1] Channel: ['0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
>>>
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Hello World!

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>>
>>> import scantest
Scan of Main I2C Channel:['0x70']
Scan of TCA[0] Channel: ['0x70']
Scan of TCA[1] Channel: ['0x70']
Scan of TCA[2] Channel: ['0x70']
Scan of TCA[3] Channel: ['0x70']
Scan of TCA[4] Channel: ['0x70']
Scan of TCA[5] Channel: ['0x70']
Scan of TCA[6] Channel: ['0x70']
Scan of TCA[7] Channel: ['0x70']
>>> 

```
and now the I2C is failing on the RP2040
```Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test.py", line 22, in <module>
  File "adafruit_tlv493d.py", line 106, in __init__
ValueError: No I2C device at address: 5e
```

2021-05-23 12:57 UTC, jposada202020 commented
Yes I see some of these results also, the 0x8 ghost is present in the nRF52840, and I have seen in folks commenting about these in discord

2021-05-23 13:26 UTC, jerryneedell commented
just FYI -- I connected the 2 sensors directlt to the RP2040 with teh tca9548a still connected and an I2C scan looks normal
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import i2c_scan
Scanning I2C bus
0x23
0x5e
0x70
3 device(s) found on I2C bus
>>> 
>>> 
soft reboot
```
and the sensors work normally
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import test_i2c
X: 0.0, Y: -0.098, Z: -0.196 mT
3.75 Lux
X: 0.294, Y: 0.196, Z: 0.0 mT
3.75 Lux
X: 0.0, Y: 0.196, Z: 0.0 mT
3.75 Lux
```
and repeatably....

2021-05-23 16:43 UTC, codenio commented
@jposada202020 and @jerryneedell 

```python
# Scan the Main I2C Channel present in your board
i2c.try_lock()
print("Scan of Main I2C Channel:{}".format([hex(i) for i in i2c.scan()]))
i2c.unlock()
```
I Feel that i2c.try_lock() should be added inside Adafruit_Blinka.busio.i2c.scan() to make it work across all the circuit python platforms..?  

https://github.com/adafruit/Adafruit_Blinka/blob/4320a101dd8a5f27dc528101d9a9f22c72005355/src/busio.py#L137-L139

do let me know your thoughts.

2021-05-23 17:22 UTC, jposada202020 commented
@codenio :) thanks, I think that would be a totally different PR. Blinka has work very well in different contexts, so different boards and sensors, and this is proven over time. So, I am not to keen to change a library just because one I2C Mux. But this is my opinion, and maybe not the people that work with Blink, so a PR to discuss is the best way to open that discussion

2021-05-23 17:55 UTC, codenio commented
so do i need to push the modified example with i2c.try_lock() for merging this PR..?
I had made the changes already, just wanted to confirm before pushing it.

2021-05-23 18:39 UTC, codenio commented
Could we try this example, that scans main channel before initialising TCA9548A, to debug further..? 

```
# SPDX-FileCopyrightText: 2021 codenio (Aananth K)
# SPDX-License-Identifier: MIT

# This example shows scanning of each TCA9548A channels.
import board
import busio
import adafruit_tca9548a

# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Scan the Main I2C Channel present in your board
print("Scan of Main I2C Channel:{}".format([hex(i) for i in i2c.scan()]))

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# Scan Each TCA9548A channel
for i in range(8):
    print("Scan of TCA[{}] Channel: {}".format(i, [hex(j) for j in tca[i].scan()]))
```

2021-05-23 18:46 UTC, jerryneedell commented
That still fails without a lock
``

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> 
>>> import scantest2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scantest2.py", line 13, in <module>
RuntimeError: Function requires lock
>>> 


```

2021-05-23 21:00 UTC, jposada202020 commented
@Codenio lets wait until tomorrow I will like more inputs regarding this. But for sure, if the example fails, without the lock a change is needed because user needs working code without any hardware tweaking.

2021-05-24 22:22 UTC, caternuson commented
Commented in #31 thread with link to an example.

Keep in mind the boiler plate I2C scan code without a mux involved:
```python
import board
i2c = board.I2C()
i2c.try_lock()
i2c.scan()
i2c.unlock
```
The general idea with the TCA is that each channel mimics that same behavior. Try with example linked in issue thread and see if that approach will work.

2021-05-24 22:36 UTC, jerryneedell commented
@caternuson why does the RP2040 behave differently from the M4?

2021-05-24 22:47 UTC, caternuson commented
I don't have a BH1750 to try for testing. But all the scanning I'm doing (so far at least) with a Feather RP2040 seems to work OK.

Here's an example scan sweep, with a MMA8451 on channel 1 and a MSA301 on channel 5:
```python
>>> for channel in range(8):
...     if tca[channel].try_lock():
...         print("Channel {}:".format(channel), end='')
...         tca[channel].scan()
...         tca[channel].unlock()
... 
Channel 0:[112]
Channel 1:[29, 112]
Channel 2:[112]
Channel 3:[112]
Channel 4:[112]
Channel 5:[38, 112]
Channel 6:[112]
Channel 7:[112]
>>> 
```

2021-05-24 23:03 UTC, jerryneedell commented
I have a bme680 and a tlv4930 on a feather Rp2040
I ran this ```
import adafruit_tca9548a

# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

i2c.try_lock()
# Scan the Main I2C Channel present in your board
print("Scan of Main I2C Channel:{}".format([hex(i) for i in i2c.scan()]))
i2c.unlock()

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# Scan Each TCA9548A channel
for channel in range(8):
    if tca[channel].try_lock():
        print("Channel {}:".format(channel), end='')
        tca[channel].scan()
        tca[channel].unlock()

```
and i hangs on the first channel of tht tca9548a
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> 
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:


hung

``

2021-05-24 23:04 UTC, jerryneedell commented
oh wait -- did you have the PR installed or not?

2021-05-24 23:06 UTC, jposada202020 commented
No PR, the comment was edited...

2021-05-24 23:12 UTC, jerryneedell commented
without thr PR I get 
```
Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> 
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:Channel 1:Channel 2:Channel 3:Channel 4:Channel 5:Channel 6:Channel 7:>>> 

```
and the same on an M4 -- did I type something wrong?

2021-05-24 23:17 UTC, jerryneedell commented
fixed teh code 
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:['0x70']
Channel 1:['0x5e', '0x70']
Channel 2:['0x70']
Channel 3:['0x70']
Channel 4:['0x70', '0x77']
Channel 5:['0x70']
Channel 6:['0x70']
Channel 7:['0x70']
>>> 

```
using
```
# This example shows scanning of each TCA9548A channels.
import board
import busio
import adafruit_tca9548a

# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

i2c.try_lock()
# Scan the Main I2C Channel present in your board
print("Scan of Main I2C Channel:{}".format([hex(i) for i in i2c.scan()]))
i2c.unlock()

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# Scan Each TCA9548A channel
for channel in range(8):
    if tca[channel].try_lock():
        print("Channel {}:".format(channel), end='')
        print("{}".format([hex(i) for i in tca[channel].scan()]))
        tca[channel].unlock()


```

2021-05-24 23:20 UTC, jerryneedell commented
Now the scan works -- wit the bh1750 , but I cant access it
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> 
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:['0x70']
Channel 1:['0x5e', '0x70']
Channel 2:['0x70']
Channel 3:['0x70']
Channel 4:['0x23', '0x70']
Channel 5:['0x70']
Channel 6:['0x70']
Channel 7:['0x70']
>>> 
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Hello World!

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test.py", line 22, in <module>
  File "adafruit_tlv493d.py", line 106, in __init__
ValueError: No I2C device at address: 5e
>>> 

```

2021-05-24 23:20 UTC, caternuson commented
I'm also using 6.2.0. I added a BME680 and TLV4930 to channel 3. Running your scan code above, I get:
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:['0x70']
Channel 1:['0x1d', '0x70']
Channel 2:['0x70']
Channel 3:['0x5e', '0x70', '0x77']
Channel 4:['0x70']
Channel 5:['0x26', '0x38', '0x70']
Channel 6:['0x70']
Channel 7:['0x70']
>>> 
```

2021-05-24 23:22 UTC, jposada202020 commented
For me with jerryn code, with a BH1750 it hangs in Channel 0.
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import testing_pt
Scan of Main I2C Channel:['0x70']
Channel 0:


```

2021-05-24 23:25 UTC, jerryneedell commented
@jposada202020 tasth is wit the PR, correct? I have reverted to the pre-PR library

2021-05-24 23:27 UTC, jerryneedell commented
the same code  as above runs OK on a feather M4 -- 
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather M4 Express with samd51j19
>>> import tca9548a_test
X: -0.196, Y: 0.294, Z: -0.294 mT
55.00 Lux
X: 0.098, Y: 0.294, Z: 0.0 mT
53.75 Lux
X: 0.0, Y: 0.392, Z: -0.098 mT
53.75 Lux
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test.py", line 28, in <module>
KeyboardInterrupt: 
>>> 


```

2021-05-24 23:27 UTC, jposada202020 commented
Thanks @jerryneedell my bad.. 

```python
>>> import testing_pt
Scan of Main I2C Channel:['0x70']
Channel 0:['0x70']
Channel 1:['0x1d', '0x70']
Channel 2:['0x70']
Channel 3:['0x70']
Channel 4:['0x23', '0x70']
Channel 5:['0x70']
Channel 6:['0x70']
Channel 7:['0x70']
```

2021-05-24 23:30 UTC, jerryneedell commented
so - the scans are now fine on RP2040, but it won't access the sensor -- at least not the tlv4930  ...

2021-05-24 23:34 UTC, jerryneedell commented
sometimes I get this as well on the RP2040
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test.py", line 21, in <module>
  File "adafruit_bh1750.py", line 191, in __init__
  File "adafruit_bh1750.py", line 196, in initialize
  File "adafruit_bh1750.py", line 116, in __set__
  File "adafruit_bh1750.py", line 205, in _settings
  File "adafruit_bh1750.py", line 235, in _write
  File "adafruit_tca9548a.py", line 54, in unlock
OSError: [Errno 19] Unsupported operation
>>> 


```

2021-05-24 23:34 UTC, caternuson commented
Seems OK using my same setup as above.
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import board
>>> import adafruit_tca9548a
>>> import adafruit_tlv493d
>>> tca = adafruit_tca9548a.TCA9548A(board.I2C())
>>> tlv = adafruit_tlv493d.TLV493D(tca[3])
>>> tlv.magnetic
(0.294, 0.196, 0.0)
>>> 
```

2021-05-24 23:35 UTC, jposada202020 commented
I retried the following code in the RP2040
```python
import time
import board
import adafruit_mma8451
import adafruit_tca9548a
import adafruit_bh1750

# import test_two_sensors

i2c = board.I2C()
tca = adafruit_tca9548a.TCA9548A(i2c)
sensor = adafruit_mma8451.MMA8451(tca[1])
sensor2 = adafruit_bh1750.BH1750(tca[4])

while True:
    x, y, z = sensor.acceleration
    print(
        "Acceleration: x={0:0.3f}m/s^2 y={1:0.3f}m/s^2 z={2:0.3f}m/s^2".format(x, y, z)
    )
    time.sleep(1)
    print("%.2f Lux" % sensor2.lux)
    time.sleep(1)
```
### Results
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import test_two_sensors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_two_sensors.py", line 12, in <module>
  File "/lib/adafruit_bh1750.py", line 164, in __init__
ValueError: No I2C device at address: 23
>>> 
```

2021-05-24 23:42 UTC, jerryneedell commented
and I tried swaping a bm3680 fr the tlv4930 and I get
```

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test2.py", line 22, in <module>
  File "adafruit_bme680.py", line 434, in __init__
ValueError: No I2C device at address: 77
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Hello World!

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import scantest2
Scan of Main I2C Channel:['0x70']
Channel 0:['0x70']
Channel 1:['0x70', '0x77']
Channel 2:['0x70']
Channel 3:['0x70']
Channel 4:['0x23', '0x70']
Channel 5:['0x70']
Channel 6:['0x70']
Channel 7:['0x70']
>>> 

```

2021-05-24 23:45 UTC, jerryneedell commented
here is my test code
```

# This example shows using two TSL2491 light sensors attached to TCA9548A channels 0 and 1.
# Use with other I2C sensors would be similar.
import time
import board
import busio
import adafruit_tca9548a
import adafruit_bh1750
import adafruit_bme680


# Create I2C bus as normal
i2c = busio.I2C(board.SCL, board.SDA)

# Create the TCA9548A object and give it the I2C bus
tca = adafruit_tca9548a.TCA9548A(i2c)

# For each sensor, create it using the TCA9548A channel instead of the I2C object
bh = adafruit_bh1750.BH1750(tca[4])
bme = adafruit_bme680.Adafruit_BME680_I2C(tca[1])

# After initial setup, can just use sensors as normal.
while True:
    print("temperature" % bme.temperature)
    print("%.2f Lux" % bh.lux)
    time.sleep(1)
```

2021-05-24 23:46 UTC, jposada202020 commented
So it is fair to say that conclusions so far:
1. PR is not needed to scan the channels
2. The TCA works for some sensors and it does not for others?

2021-05-24 23:49 UTC, jerryneedell commented
#2 only applies to the RP2040

2021-05-24 23:50 UTC, caternuson commented
I believe so. Adding a new example, and maybe a doc update, might help though?

Is the BH1750 the suspect sensor here? I'm not having any issues with TLV4930, BME680, AHT20, MSA301, MMA8451. All being used with Feather RP2040 and 6.2.0 release of CP.

2021-05-24 23:51 UTC, jposada202020 commented
Yes, I forgot that part, you are correct!

2021-05-24 23:51 UTC, jerryneedell commented
@caternuson can you configure and access two sensors on the RP2040?

2021-05-24 23:55 UTC, caternuson commented
@jerryneedell seems like it.
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import board
>>> import adafruit_tca9548a
>>> import adafruit_tlv493d
>>> import adafruit_msa301
>>> tca = adafruit_tca9548a.TCA9548A(board.I2C())
>>> tlv = adafruit_tlv493d.TLV493D(tca[3])
>>> msa = adafruit_msa301.MSA301(tca[5])
>>> tlv.magnetic
(0.196, -0.196, 0.0)
>>> msa.acceleration
(0.871432, 3.95975, 10.4572)
>>> 
```

2021-05-24 23:56 UTC, jerryneedell commented
yikes! the bme680 and tlv4930 work on the rp2040,,,,
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import tca9548a_test
X: 0.098, Y: 0.196, Z: -0.098 mT
24.25 temperature
X: -0.098, Y: 0.0, Z: 0.0 mT
24.27 temperature
X: 0.0, Y: 0.0, Z: 0.0 mT
```

2021-05-24 23:57 UTC, jerryneedell commented
I surrender...  
I will banish the bh1750 and forget this ever happened

2021-05-24 23:58 UTC, jposada202020 commented
So I think we all agree, if you all agree I could make a PR to clarify the documentation, to mentions the BH1750 (I would retest to be 100% sure), and add a new example trying to reflect all this discussion. let me know if you agree :)

2021-05-24 23:59 UTC, jerryneedell commented
still -- no clue why the bht1750 only misbehaves on the RP2040 with the tca9548a....
not sure how to document that...

2021-05-25 00:03 UTC, jerryneedell commented
I would suggest a new channelscan example and a new issue regarding the bht1750.

2021-05-25 00:03 UTC, jposada202020 commented
Normally we include a section in # Kwnow Issues.
I do not have a Saleae, and Cater does not have the sensor, so in the meantime we could do this

2021-05-25 00:04 UTC, jerryneedell commented
I have a Salea and I can try to dig into the bht1750 tomorrow

2021-05-25 00:07 UTC, jposada202020 commented
@jerryneedell  you said... that you would banish the BHT1750 and forget about this.. ... so I thought the sensor was already in the garbage bin 😄

2021-05-25 00:08 UTC, jerryneedell commented
I just gave it to the cat lo play with -- she gave it back. ;-)

2021-05-25 00:13 UTC, caternuson commented
Yep. I generally agree with above. It looks like this all started with an issue about being able to do I2C scans with TCA, and I think it could, just wasn't obvious how - so a new example will help with that.

For the BHT1750 - yah, who knows. I'll order one up and can test when I get it. But that should be a new issue.

2021-05-25 00:14 UTC, jerryneedell commented
so -- I tried just the bh1750 on the tca9548a an then the bh1750 dircet to the stemma I2c
```
Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> 
>>> import tca9548a_test3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tca9548a_test3.py", line 20, in <module>
  File "adafruit_bh1750.py", line 191, in __init__
  File "adafruit_bh1750.py", line 196, in initialize
  File "adafruit_bh1750.py", line 116, in __set__
  File "adafruit_bh1750.py", line 205, in _settings
  File "adafruit_bh1750.py", line 235, in _write
  File "adafruit_tca9548a.py", line 54, in unlock
OSError: [Errno 19] Unsupported operation
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Hello World!

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.2-646-g7df5d74d9 on 2021-05-23; Adafruit Feather RP2040 with rp2040
>>> import bh1750_simpletest
12.92 Lux
12.92 Lux
```

2021-05-25 00:15 UTC, jerryneedell commented
I wonder if it could be something as simple as the wires being too long for the tca.

2021-05-25 00:20 UTC, jerryneedell commented
I'll be happy to try hooking up my salea to the bht1750 tomorrow and see if I can learn anything. I will also create a new issue for it after I clean up my test code  (and my bench). Or @jposada202020  since you have the bh1750 -- you are welcome to create an issue  and I'll add to it.

2021-05-25 00:25 UTC, jposada202020 commented
Will do @jerryneedell I ll create the issue, I just want to test one more time to be 100%, and maybe try some other random sensors :) maybe the ADT7410.. who knows :)

2021-05-25 03:54 UTC, jposada202020 commented
So after I successful test this fails again.

However, there is a difference between testing in the REPL as @caternuson does and doing it with a File as @jerryneedell  and myself do

## File --> FAIL
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import test_two_sensors
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_two_sensors.py", line 13, in <module>
  File "/lib/adafruit_bh1750.py", line 164, in __init__
ValueError: No I2C device at address: 23
```

## REPL --> OK
```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import time
>>> import board
>>> import adafruit_mma8451
>>> import adafruit_tca9548a
>>> import adafruit_bh1750
>>> i2c = board.I2C()
>>> tca = adafruit_tca9548a.TCA9548A(i2c)
>>> sensor = adafruit_mma8451.MMA8451(tca[1])
>>> sensor2 = adafruit_bh1750.BH1750(tca[4])
>>> while True:
...     x, y, z = sensor.acceleration
...     print("Acceleration: x={0:0.3f}m/s^2 y={1:0.3f}m/s^2 z={2:0.3f}m/s^2".format(x, y, z))
...     print("%.2f Lux" % sensor2.lux)
...     time.sleep(1)
... 
Acceleration: x=-0.192m/s^2 y=0.350m/s^2 z=9.783m/s^2
1152.92 Lux
Acceleration: x=-0.249m/s^2 y=0.388m/s^2 z=9.778m/s^2
1152.08 Lux
Acceleration: x=-0.268m/s^2 y=0.378m/s^2 z=9.831m/s^2
1152.92 Lux
```

Could this be related to the clock on the RP2040?

And have a good night... I could not go to bed with this :)

2021-05-25 08:32 UTC, codenio commented
> So it is fair to say that conclusions so far:
> 
> 1. PR is not needed to scan the channels

@jposada202020 
yes, if you suggest ppl to use `try_lock()` and `unlock()` **consciously while scanning any channel, at any time and every time**.


> Keep in mind the boiler plate I2C scan code without a mux involved:
```python
import board
i2c = board.I2C()
i2c.try_lock()
i2c.scan()
i2c.unlock()
```
@caternuson  This PR does exactly the same, but in an abstract way by including `try_lock` and `unlock` inside the scan function itself.

It couldn't find such requirements of explicit locking and unlocking with writing data into or read data from an i2c device (as they are abstracted within them).

I feel that `try_lock()` and `unlock()` need to be abstracted inside the scan function.

Thought..?

2021-05-25 10:09 UTC, jerryneedell commented
In some quick tests this morning, I am finding that I can access either the bh1750 or the bme680 individually via the tca9548a but I get failures when I try to access both. In most cases the failure is on the one I attempt to configure second.
Sometimes the system get in  a bad state ( gives "unsupported operation error) and I have to do a hard reset to get it working normally again. 
This has nothing to do with this PR so  I will stop posting to this PR after this and will see if I can come up with a coherent new issue.

2021-05-25 10:19 UTC, jerryneedell commented
Regarding the scan and try_lock,  for the normal I2C scan (without the tca9548a) the user must secure the lock manually.
I don't know the history for why is is not done by the scan function but I suggest we keep it consistent. 
the busio scan function checks for the lock https://github.com/adafruit/circuitpython/blob/main/shared-bindings/busio/I2C.c#L139

If we want it to be done internally, I think the change needs to be made in the core.
I am not advocating that just pointing it out.

2021-05-25 10:47 UTC, jposada202020 commented
@jerryneedell I have opened #33 . If needed we could move that issue to whatever the issue is. this way we could stop posting here

2021-05-25 15:18 UTC, caternuson commented
I think `tca[n].scan()` should behave the same as `i2c.scan()`. So the need to manually lock/unlock the bus should be retained. Which agrees with @jerryneedell comments above about same.

2021-05-25 16:08 UTC, jposada202020 commented
So after all this discussion I think this PR is no longer required. The issue is already raise, I will add another issue, to keep track of adding the new example to reflect our findings in here
@codenio Thanks this was a helpful and constructive discussion

2021-06-14 21:49 UTC, caternuson commented
> So after all this discussion I think this PR is no longer required.

I agree. There seems to be some other potentially tangential issues that have been raised above, but those should be dealt with separately. Closing this PR for now. Thanks for the work on this. Lots of good discussion in this thread. :)

2021-06-14 21:49 UTC, closed without merging

2024-06-08 05:15 UTC, Wongolini commented
> I did a retake on this
> # Wiring
> 
> ![image](https://user-images.githubusercontent.com/34255413/119245367-db858e80-bb46-11eb-9038-b90f83980e13.png)
> # Results
> 
> This PR works, with a SAMD51, and the nRF52840, however it does not work for the RP2040. I tested this with the code mentioned above, and with a modified simpletest to include two sensor and not one. Sensor were a BH1750 and a MMA8451
> ## SAMD51
> 
> ```python
> Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather M4 Express with samd51j19
> >>> import tca9548_scantest
> Scan of Main I2C Channel:['0x70']
> Scan of TCA[0] Channel: ['0x70']
> Scan of TCA[1] Channel: ['0x1d', '0x70']
> Scan of TCA[2] Channel: ['0x70']
> Scan of TCA[3] Channel: ['0x70']
> Scan of TCA[4] Channel: ['0x23', '0x70']
> Scan of TCA[5] Channel: ['0x70']
> Scan of TCA[6] Channel: ['0x70']
> Scan of TCA[7] Channel: ['0x70']
> ```
> 
> ```python
> >>> import tca9548a_simpletest
> Acceleration: x=-0.283m/s^2 y=1.097m/s^2 z=9.821m/s^2
> 346.67 Lux
> Acceleration: x=-0.354m/s^2 y=1.087m/s^2 z=9.797m/s^2
> 345.83 Lux
> ```
> 
> ## RP2040
> 
> ```python
> Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
> >>> import tca9548_scantest
> Scan of Main I2C Channel:['0x70']
> Scan of TCA[0] Channel: ['0x70']
> Scan of TCA[1] Channel: ['0x70']
> Scan of TCA[2] Channel: ['0x70']
> Scan of TCA[3] Channel: ['0x70']
> Scan of TCA[4] Channel: ['0x70']
> Scan of TCA[5] Channel: ['0x70']
> Scan of TCA[6] Channel: ['0x70']
> Scan of TCA[7] Channel: ['0x70']
> ```
> 
> ```python
> Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
> >>> import tca9548a_simpletest
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "tca9548a_simpletest.py", line 11, in <module>
>   File "/lib/adafruit_bh1750.py", line 164, in __init__
> ValueError: No I2C device at address: 23
> ```
> 
> ## nRF52840
> 
> ```python
> Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather nRF52840 Express with nRF52840
> >>> import tca9548a_simpletest
> Acceleration: x=-0.273m/s^2 y=1.135m/s^2 z=9.802m/s^2
> 322.08 Lux
> ```
> 
> ```python
> Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather nRF52840 Express with nRF52840
> >>> import tca9548_scantest
> Scan of Main I2C Channel:['0x8', '0x70']
> Scan of TCA[0] Channel: ['0x8', '0x70']
> Scan of TCA[1] Channel: ['0x8', '0x1d', '0x70']
> Scan of TCA[2] Channel: ['0x8', '0x70']
> Scan of TCA[3] Channel: ['0x8', '0x70']
> Scan of TCA[4] Channel: ['0x8', '0x23', '0x70']
> Scan of TCA[5] Channel: ['0x8', '0x70']
> Scan of TCA[6] Channel: ['0x8', '0x70']
> Scan of TCA[7] Channel: ['0x8', '0x70']
> >>> 
> ```
> 
> ## Test Code
> 
> ```python
> import time
> import board
> import adafruit_mma8451
> import adafruit_tca9548a
> import adafruit_bh1750
> 
> i2c = board.I2C()
> tca = adafruit_tca9548a.TCA9548A(i2c)
> sensor = adafruit_mma8451.MMA8451(tca[1])
> sensor2 = adafruit_bh1750.BH1750(tca[4])
> 
> while True:
>     x, y, z = sensor.acceleration
>     print(
>         "Acceleration: x={0:0.3f}m/s^2 y={1:0.3f}m/s^2 z={2:0.3f}m/s^2".format(x, y, z)
>     )
>     time.sleep(1)
>     print("%.2f Lux" % sensor2.lux)
>     time.sleep(1)
> ```

Has anyone found a reason this does not work for RP2040? I wanted to use this with a RasperryPi Pico but was disappointed to reproduce this error.